services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: 
      - .env

  streamlit:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://fastapi:8000 
    depends_on:
      - fastapi 
